
export const dummychar = {
    "codepoint": "U+9673",
    "kanji": "陳",
    "on": "チン",
    "pinyin": "chén",
    "jyutping": "can4 can2 zan6",
    "kun": "ひ.ねる、の.べる、つら.ねる、ふる.い",
    "meaning": "exhibit; line up; set forth",
    "tags": "会意, 常用",
    "variants": "陈,陣,阵,𨸬",
    "JP shinjitai form": "",
    "idc_analysis": "",
    "idc_naive": "⿰阝東",
    "意": "阝",
    "聲": "",
    "原聲": "",
    "最原聲": "",
    "root_phonetic_search": "",
    "聲 pinyin": "",
    "聲 on": "",
    "聲 jyutping": "",
    "components": "日木東阝陳",
    "romaji_search": "chin hineru noberu tsuraneru furui chen can4 can2 zan6 exhibit;line up;set forth",
    "on_romaji": "chin",
    "kun_romaji": "hineru noberu tsuraneru furui",
    "freq_jp": "2352",
    "freq_zh": "9000",
    "inclusion_jomako": "0.00%",
    "inclusion_all": "1.92%",
    "high frequency words": null,
    "mid frequency words": null,
    "low frequency words": null,
    "extremely rare words": null,
    "proper nouns": null
}

export const dummychararray = [
    {
        "kanji": "假",
        "on": "カ、ケ",
        "pinyin": "jiǎ",
        "jyutping": "gaa2 gaa1 gaa3 haa4",
        "kun": "かり、かり.る、か.す",
        "meaning": "temporary; interim; assumed (name); informal",
        "tags": "形声, 旧字体",
        "variants": "仮",
        "JP shinjitai form": "仮",
        "idc_analysis": "",
        "idc_naive": "⿰亻叚",
        "意": "亻",
        "聲": "叚",
        "原聲": "",
        "最原聲": "",
        "root_phonetic_search": "叚",
        "components": "⑤コ亻假又叚",
        "on_romaji": "ka ke",
        "kun_romaji": "kari kariru kasu",
        "freq_jp": 3231,
        "freq_zh": 635,
        "inclusion_jomako": 0,
        "inclusion_all": 0.0025977016788337978
    },
    {
        "kanji": "亻",
        "on": "イ",
        "pinyin": "rén",
        "jyutping": "jan4 kei5.jan4.bin1",
        "kun": " にんべん",
        "meaning": "radical number 9",
        "tags": "",
        "variants": "人",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "亻",
        "意": "",
        "聲": "",
        "原聲": "",
        "最原聲": "",
        "root_phonetic_search": "",
        "components": "亻",
        "on_romaji": "i",
        "kun_romaji": "ninben",
        "freq_jp": 6561,
        "freq_zh": 9000,
        "inclusion_jomako": 0,
        "inclusion_all": 0.00004605854040485457
    },
    {
        "kanji": "反",
        "on": "ハン、ホン*、タン*",
        "pinyin": "fǎn",
        "jyutping": "faan2 faan1",
        "kun": "そ.る、そ.らす、かえ.す、かえ.る、そむ.く",
        "meaning": "anti-; counter",
        "tags": "会意, 常用",
        "variants": "",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿸厂又",
        "意": "",
        "聲": "",
        "原聲": "",
        "最原聲": "",
        "root_phonetic_search": "",
        "components": "厂又反",
        "on_romaji": "han hon* tan*",
        "kun_romaji": "soru sorasu kaesu kaeru somuku",
        "freq_jp": 382,
        "freq_zh": 237,
        "inclusion_jomako": 0.6775,
        "inclusion_all": 0.1585703429058333
    },
    {
        "kanji": "叚",
        "on": "カ",
        "pinyin": "xiá jiǎ",
        "jyutping": "gaa2",
        "kun": "か.りる、か.す",
        "meaning": "false",
        "tags": "闕",
        "variants": "",
        "JP shinjitai form": "",
        "idc_analysis": "叚",
        "idc_naive": "⿰⑤⿱コ又",
        "意": "",
        "聲": "",
        "原聲": "",
        "最原聲": "",
        "root_phonetic_search": "",
        "components": "⑤コ又叚叚",
        "on_romaji": "ka",
        "kun_romaji": "kariru kasu",
        "freq_jp": 9684,
        "freq_zh": 9000,
        "inclusion_jomako": 0,
        "inclusion_all": 0.000004605854040485457
    },
    {
        "kanji": "仮",
        "on": "カ、ケ*",
        "pinyin": "fǎn",
        "jyutping": "faan2",
        "kun": "かり、か.す",
        "meaning": "sham; provisional; temporary",
        "tags": "新字体, 常用, 形声",
        "variants": "假",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿰亻反",
        "意": "亻",
        "聲": "叚",
        "原聲": "",
        "最原聲": "",
        "root_phonetic_search": "叚",
        "components": "⑤コ亻仮厂又反叚",
        "on_romaji": "ka ke*",
        "kun_romaji": "kari kasu",
        "freq_jp": 730,
        "freq_zh": 9000,
        "inclusion_jomako": 0.5475,
        "inclusion_all": 0.06461092047992999
    },
    {
        "codepoint": "U+86A3",
        "kanji": "蚣",
        "on": "コウ、ショウ、ク、シュ",
        "pinyin": "gōng",
        "jyutping": "gung1",
        "kun": "",
        "meaning": "centipede; grasshopper",
        "tags": "形声, 或字",
        "variants": "",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿰虫公",
        "意": "虫",
        "聲": "公",
        "原聲": "",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "八公厶虫蚣",
        "on_romaji": "kou shou ku shu",
        "kun_romaji": "",
        "freq_jp": 5214,
        "freq_zh": 4098,
        "inclusion_jomako": 0,
        "inclusion_all": 0.00020726343182184557,
        "romaji_search": "kou shou ku shu gong gung1 centipede;grasshopper"
    },
    {
        "codepoint": "U+3750",
        "kanji": "㝐",
        "on": "ヨウ",
        "pinyin": "róng",
        "jyutping": "jung4",
        "kun": "",
        "meaning": "(ancient form of 容) face; expression, to contain; to hold; to pardon",
        "tags": "形声, 古文",
        "variants": "",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿱宀公",
        "意": "宀",
        "聲": "公",
        "原聲": "",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "㝐八公厶宀",
        "on_romaji": "you",
        "kun_romaji": "",
        "freq_jp": 9000,
        "freq_zh": 9000,
        "inclusion_jomako": 0,
        "inclusion_all": 0,
        "romaji_search": "you rong jung4 (ancient form of 容) face; expression, to contain; to hold; to pardon"
    },
    {
        "codepoint": "U+8BBC",
        "kanji": "讼",
        "on": "(訟) ショウ",
        "pinyin": "sòng",
        "jyutping": "zung6",
        "kun": "",
        "meaning": "accuse; argue, dispute; litigate",
        "tags": "形声, 簡体",
        "variants": "訟",
        "JP shinjitai form": "訟",
        "idc_analysis": "",
        "idc_naive": "⿰讠公",
        "意": "讠",
        "聲": "公",
        "原聲": "",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "八公厶讠讼",
        "on_romaji": "shou",
        "kun_romaji": "",
        "freq_jp": 9000,
        "freq_zh": 1859,
        "inclusion_jomako": 0,
        "inclusion_all": 0,
        "romaji_search": "shou song zung6 accuse; argue, dispute; litigate"
    },
    {
        "codepoint": "U+9882",
        "kanji": "颂",
        "on": "(頌) ショウ、ズ、ジュ",
        "pinyin": "sòng",
        "jyutping": "zung6",
        "kun": "",
        "meaning": "laud, acclaim; hymn; ode",
        "tags": "形声, 簡体",
        "variants": "頌",
        "JP shinjitai form": "頌",
        "idc_analysis": "",
        "idc_naive": "⿰公页",
        "意": "页",
        "聲": "公",
        "原聲": "",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "八公厶页颂",
        "on_romaji": "shou zu ju",
        "kun_romaji": "",
        "freq_jp": 8224,
        "freq_zh": 2409,
        "inclusion_jomako": 0,
        "inclusion_all": 0.000009211708080970914,
        "romaji_search": "shou zu ju song zung6 laud, acclaim; hymn; ode"
    },
    {
        "codepoint": "U+8A1F",
        "kanji": "訟",
        "on": "ショウ",
        "pinyin": "sòng",
        "jyutping": "zung6",
        "kun": "うった.える",
        "meaning": "sue; litigate",
        "tags": "形声, 常用",
        "variants": "讼",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿰言公",
        "意": "言",
        "聲": "公",
        "原聲": "",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "䇂八公厶口言訟",
        "on_romaji": "shou",
        "kun_romaji": "uttaeru",
        "freq_jp": 2197,
        "freq_zh": 9000,
        "inclusion_jomako": 0.0425,
        "inclusion_all": 0.010224995969877715,
        "romaji_search": "shou uttaeru song zung6 sue;litigate"
    },
    {
        "codepoint": "U+980C",
        "kanji": "頌",
        "on": "ショウ、ズ、ジュ",
        "pinyin": "sòng",
        "jyutping": "zung6",
        "kun": "かたち、たた.える、ほめ.る、ほ.める、ゆる.やか",
        "meaning": "eulogy",
        "tags": "形声, 人名用",
        "variants": "颂",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿰公頁",
        "意": "頁",
        "聲": "公",
        "原聲": "",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "八公厶頁頌",
        "on_romaji": "shou zu ju",
        "kun_romaji": "katachi tataeru homeru homeru yuruyaka",
        "freq_jp": 3323,
        "freq_zh": 9000,
        "inclusion_jomako": 0,
        "inclusion_all": 0.002279897750040301,
        "romaji_search": "shou zu ju katachi tataeru homeru homeru yuruyaka song zung6 eulogy"
    },
    {
        "codepoint": "U+677E",
        "kanji": "松",
        "on": "ショウ",
        "pinyin": "sōng",
        "jyutping": "cung4 cung2 sung1",
        "kun": "まつ",
        "meaning": "pine tree; pine",
        "tags": "形声, 簡体, 常用",
        "variants": "鬆",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿰木公",
        "意": "木",
        "聲": "公",
        "原聲": "",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "八公厶木松",
        "on_romaji": "shou",
        "kun_romaji": "matsu",
        "freq_jp": 1663,
        "freq_zh": 893,
        "inclusion_jomako": 0.0775,
        "inclusion_all": 0.171498975197476,
        "romaji_search": "shou matsu song cung4 cung2 sung1 pine tree;pine"
    },
    {
        "codepoint": "U+83D8",
        "kanji": "菘",
        "on": "シュウ、スウ",
        "pinyin": "sōng",
        "jyutping": "sung1",
        "kun": "すずな、つけな、とうな",
        "meaning": "type of rape plant",
        "tags": "形声",
        "variants": "",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿱艹松",
        "意": "艹",
        "聲": "松",
        "原聲": "公",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "丨八公十厶木松艹菘",
        "on_romaji": "shuu suu",
        "kun_romaji": "suzuna tsukena touna",
        "freq_jp": 5645,
        "freq_zh": 5908,
        "inclusion_jomako": 0,
        "inclusion_all": 0.00012435805909310734,
        "romaji_search": "shuu suu suzuna tsukena touna song sung1 type of rape plant"
    },
    {
        "codepoint": "U+6DDE",
        "kanji": "淞",
        "on": "ショウ、シュ",
        "pinyin": "sōng",
        "jyutping": "sung1",
        "kun": "",
        "meaning": "name of a Chinese river",
        "tags": "形声",
        "variants": "",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿰氵松",
        "意": "氵",
        "聲": "松",
        "原聲": "公",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "八公厶木松氵淞",
        "on_romaji": "shou shu",
        "kun_romaji": "",
        "freq_jp": 5132,
        "freq_zh": 4031,
        "inclusion_jomako": 0,
        "inclusion_all": 0.00023029270202427286,
        "romaji_search": "shou shu song sung1 name of a Chinese river"
    },
    {
        "codepoint": "U+9B06",
        "kanji": "鬆",
        "on": "ショウ、シュ、ソウ",
        "pinyin": "sōng",
        "jyutping": "sung1",
        "kun": "あら.い、ゆる.い、す",
        "meaning": "loose; dishevelled; pore; cavity in overboiled daikon",
        "tags": "形声",
        "variants": "松",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿱髟松",
        "意": "髟",
        "聲": "松",
        "原聲": "公",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "八公厶彡木松長镸髟鬆",
        "on_romaji": "shou shu sou",
        "kun_romaji": "arai yurui su",
        "freq_jp": 4609,
        "freq_zh": 9000,
        "inclusion_jomako": 0,
        "inclusion_all": 0.0004421619878866039,
        "romaji_search": "shou shu sou arai yurui su song sung1 loose;dishevelled;pore;cavity in overboiled daikon"
    },
    {
        "codepoint": "U+8719",
        "kanji": "蜙",
        "on": "ショウ、シュ、ソウ、ス、シュウ",
        "pinyin": "sōng",
        "jyutping": "sung1",
        "kun": " ",
        "meaning": "",
        "tags": "形声",
        "variants": "",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿰虫松",
        "意": "虫",
        "聲": "松",
        "原聲": "公",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "八公厶木松虫蜙",
        "on_romaji": "shou shu sou su shuu",
        "kun_romaji": "",
        "freq_jp": 7508,
        "freq_zh": 9500,
        "inclusion_jomako": 0,
        "inclusion_all": 0.000018423416161941828,
        "romaji_search": "shou shu sou su shuu song sung1"
    },
    {
        "codepoint": "U+84CA",
        "kanji": "蓊",
        "on": "オウ、ウ",
        "pinyin": "wěng",
        "jyutping": "jung2",
        "kun": "とう",
        "meaning": "flower stalk; vigorous growth",
        "tags": "形声",
        "variants": "",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿱艹翁",
        "意": "艹",
        "聲": "翁",
        "原聲": "公",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "丨八公十厶羽翁艹蓊",
        "on_romaji": "ou u",
        "kun_romaji": "tou",
        "freq_jp": 5049,
        "freq_zh": 6150,
        "inclusion_jomako": 0,
        "inclusion_all": 0.0002533219722267001,
        "romaji_search": "ou u tou weng jung2 flower stalk;vigorous growth"
    },
    {
        "codepoint": "U+7FC1",
        "kanji": "翁",
        "on": "オウ",
        "pinyin": "wēng",
        "jyutping": "jung1",
        "kun": "おきな",
        "meaning": "venerable old man; old man",
        "tags": "形声, 常用",
        "variants": "",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿱公羽",
        "意": "羽",
        "聲": "公",
        "原聲": "",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "习八公厶羽翁",
        "on_romaji": "ou",
        "kun_romaji": "okina",
        "freq_jp": 2523,
        "freq_zh": 2108,
        "inclusion_jomako": 0,
        "inclusion_all": 0.009750593003707713,
        "romaji_search": "ou okina weng jung1 venerable old man;old man"
    },
    {
        "codepoint": "U+9E5F",
        "kanji": "鹟",
        "on": "(鶲) オウ、オ",
        "pinyin": "wēng",
        "jyutping": "jung1",
        "kun": "",
        "meaning": "",
        "tags": "形声, 簡体",
        "variants": "鶲",
        "JP shinjitai form": "鶲",
        "idc_analysis": "",
        "idc_naive": "⿰翁鸟",
        "意": "鸟",
        "聲": "翁",
        "原聲": "公",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "④一八公厶羽翁鸟鹟",
        "on_romaji": "ou o",
        "kun_romaji": "",
        "freq_jp": 9500,
        "freq_zh": 7008,
        "inclusion_jomako": 0,
        "inclusion_all": 0,
        "romaji_search": "ou o weng jung1"
    },
    {
        "codepoint": "U+6EC3",
        "kanji": "滃",
        "on": "オ、オウ",
        "pinyin": "wēng",
        "jyutping": "jung2 jung1",
        "kun": " ",
        "meaning": "swelling, rising, dispersing",
        "tags": "形声",
        "variants": "",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿰氵翁",
        "意": "氵",
        "聲": "翁",
        "原聲": "公",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "八公厶氵滃羽翁",
        "on_romaji": "o ou",
        "kun_romaji": "",
        "freq_jp": 7508,
        "freq_zh": 9000,
        "inclusion_jomako": 0,
        "inclusion_all": 0.000018423416161941828,
        "romaji_search": "o ou weng jung2 jung1 swelling, rising, dispersing"
    },
    {
        "codepoint": "U+4235",
        "kanji": "䈵",
        "on": "オウ、オ",
        "pinyin": "wēng",
        "jyutping": "jung1",
        "kun": " ",
        "meaning": "luxuriant; exuberant of bamboo",
        "tags": "形声",
        "variants": "",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿱竹翁",
        "意": "竹",
        "聲": "翁",
        "原聲": "公",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "䈵亇八公厶竹羽翁",
        "on_romaji": "ou o",
        "kun_romaji": "",
        "freq_jp": 8224,
        "freq_zh": 9000,
        "inclusion_jomako": 0,
        "inclusion_all": 0.000009211708080970914,
        "romaji_search": "ou o weng jung1 luxuriant; exuberant of bamboo"
    },
    {
        "codepoint": "U+9DB2",
        "kanji": "鶲",
        "on": "オウ、オ",
        "pinyin": "wēng",
        "jyutping": "jung1",
        "kun": "ひたき",
        "meaning": "crested flycatcher; peewee",
        "tags": "形声",
        "variants": "鹟",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿰翁鳥",
        "意": "鳥",
        "聲": "翁",
        "原聲": "公",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "⑦八公厶灬羽翁鳥鶲",
        "on_romaji": "ou o",
        "kun_romaji": "hitaki",
        "freq_jp": 5612,
        "freq_zh": 9000,
        "inclusion_jomako": 0,
        "inclusion_all": 0.0001289639131335928,
        "romaji_search": "ou o hitaki weng jung1 crested flycatcher;peewee"
    },
    {
        "codepoint": "U+4C75",
        "kanji": "䱵",
        "on": "オウ、オ",
        "pinyin": "wēng",
        "jyutping": "jung1",
        "kun": " ",
        "meaning": "a kind of fish; live in the ocean",
        "tags": "形声",
        "variants": "𮬢",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿰魚翁",
        "意": "魚",
        "聲": "翁",
        "原聲": "公",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "䱵八公厶灬田羽翁魚𠂊",
        "on_romaji": "ou o",
        "kun_romaji": "",
        "freq_jp": 9000,
        "freq_zh": 9000,
        "inclusion_jomako": 0,
        "inclusion_all": 0,
        "romaji_search": "ou o weng jung1 a kind of fish; live in the ocean"
    },
    {
        "codepoint": "U+8789",
        "kanji": "螉",
        "on": "オウ、オ",
        "pinyin": "wēng",
        "jyutping": "jung1",
        "kun": " ",
        "meaning": "wasp",
        "tags": "形声",
        "variants": "",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿰虫翁",
        "意": "虫",
        "聲": "翁",
        "原聲": "公",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "八公厶羽翁虫螉",
        "on_romaji": "ou o",
        "kun_romaji": "",
        "freq_jp": 9000,
        "freq_zh": 9000,
        "inclusion_jomako": 0,
        "inclusion_all": 0,
        "romaji_search": "ou o weng jung1 wasp"
    },
    {
        "codepoint": "U+4F00",
        "kanji": "伀",
        "on": "ショウ、シュ",
        "pinyin": "zhōng",
        "jyutping": "zung1",
        "kun": " ",
        "meaning": "excited",
        "tags": "形声",
        "variants": "彸",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿰亻公",
        "意": "亻",
        "聲": "公",
        "原聲": "",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "亻伀八公厶",
        "on_romaji": "shou shu",
        "kun_romaji": "",
        "freq_jp": 9000,
        "freq_zh": 9000,
        "inclusion_jomako": 0,
        "inclusion_all": 0,
        "romaji_search": "shou shu zhong zung1 excited"
    },
    {
        "codepoint": "U+220D3",
        "kanji": "𢃓",
        "on": "ショウ",
        "pinyin": "",
        "jyutping": "",
        "kun": "",
        "meaning": "",
        "tags": "形声, 或字",
        "variants": "",
        "JP shinjitai form": "",
        "idc_analysis": "",
        "idc_naive": "⿰巾松",
        "意": "巾",
        "聲": "松",
        "原聲": "公",
        "最原聲": "",
        "root_phonetic_search": "公",
        "components": "八公厶巾木松𢃓",
        "on_romaji": "shou",
        "kun_romaji": "",
        "freq_jp": 9999,
        "freq_zh": 9999,
        "inclusion_jomako": 0,
        "inclusion_all": 0,
        "romaji_search": "shou"
    }
]

let dummySeries = {
    phonetic: dummychararray,
    semantic: dummychararray,
    form: dummychararray,
    empty: dummychararray,
    root_phonetic: dummychararray.concat(dummychararray)
}

let dummycompcharobj = {
    "kanji": "公",
    "on": "コウ",
    "pinyin": "gōng",
    "jyutping": "gung1 gung4",
    "kun": "おおやけ、きみ",
    "meaning": "public",
    "tags": "会意, 常用",
    "variants": "",
    "JP shinjitai form": "",
    "idc_analysis": "",
    "idc_naive": "⿱八厶",
    "意": "",
    "聲": "",
    "原聲": "",
    "最原聲": "",
    "root_phonetic_search": "",
    "components": "八公厶",
    "on_romaji": "kou",
    "kun_romaji": "ooyake kimi",
    "freq_jp": 405,
    "freq_zh": 115,
    "inclusion_jomako": 0.41,
    "inclusion_all": 0.4028233885268176
}


let dummycomponent = { role: 'Phonetic', charObj: dummycompcharobj, series: dummySeries }

export const dummyEntryObj = {
    consultedKanjiObj:
    {
        codepoint: 23478,
        kanji: '家',
        on: 'カ、ケ',
        pinyin: 'jiā',
        jyutping: 'gaa1 gu1 gwu1 gaa3',
        kun: 'いえ、や、うち',
        meaning: 'house; family',
        Notes: '',
        tags: '訛声, 常用',
        variants: '傢',
        'JP shinjitai form': '',
        idc_analysis: '',
        idc_naive: '⿱宀豕',
        semantic: '',
        phonetic: '',
        form: '宀',
        empty: '豕',
        root_phonetic: '𢑓',
        components: '一叚宀豕𧰨',
        kun_romaji: 'ie ya uchi',
        on_romaji: 'ka ke',
        freq_jp: 51,
        freq_zh: 56,
        inclusion_jomako: 0.905,
        inclusion_all: 0.3848375284987219,
        correct_root: '𢑓'
    },
    componentArray: [
        { role: 'form', charObj: dummycompcharobj, series: dummySeries },
        { role: 'empty', charObj: dummycompcharobj, series: dummySeries },
        { role: 'root_phonetic', charObj: dummycompcharobj, series: dummySeries }]
}
